const Mdata = [
  {
    id: 1,
    pname: "Chicken Biryani",
    category: "biryani",
    price: 369,
    imgsrc: "./images/biryani-1.jpg",
  },
  {
    id: 2,
    pname: "Margherita Pizza",
    category: "pizza",
    price: 238,
    imgsrc: "./images/pizza-1.jpg",
  },
  {
    id: 3,
    pname: "Bun Tikki Burger",
    category: "burger",
    price: 98,
    imgsrc: "./images/burger-1.jpg",
  },
  {
    id: 4,
    pname: "Veg Biryani",
    category: "biryani",
    price: 249,
    imgsrc: "./images/biryani-2.jpg",
  },
  {
    id: 5,
    pname: "Vegetable Noodles",
    category: "noodles",
    price: 249,
    imgsrc: "./images/noodles-1.jpg",
  },
  {
    id: 6,
    pname: "Paneer Tikka Biryani",
    category: "biryani",
    price: 299,
    imgsrc: "./images/biryani-3.jpg",
  },
  {
    id: 7,
    pname: "Cheese Onion Pizza",
    category: "pizza",
    price: 299,
    imgsrc: "./images/pizza-2.jpg",
  },
  {
    id: 8,
    pname: "Cheesy Chicken Pizza",
    category: "pizza",
    price: 349,
    imgsrc: "./images/pizza-3.jpg",
  },
  {
    id: 9,
    pname: "Crispy Chicken Burger",
    category: "burger",
    price: 129,
    imgsrc: "./images/burger-3.jpg",
  },
  {
    id: 10,
    pname: "Vegetable Singapore Noodles",
    category: "noodles",
    price: 385,
    imgsrc: "./images/noodles-3.jpg",
  },
  {
    id: 11,
    pname: "BBQ Chicken Burger",
    category: "burger",
    price: 189,
    imgsrc: "./images/burger-2.jpg",
  },
  {
    id: 12,
    pname: "Chicken Garlic Noodles",
    category: "noodles",
    price: 345,
    imgsrc: "./images/noodles-2.jpg",
  },
];

export default Mdata;
